announce = false

description = 'test'
website = 'test.com'
gamemode = 'Freeroam'

language = 'en'
modules = ['js-module']
name = 'My Cool alt:V Server Built With Svelte 8)'
players = 32
port = 7788
tags = ['customTag1', 'customTag2', 'customTag3', 'customTag4']

resources = [
    # Add mods here
    'webviews',
    'core',
]

# Turn this off in production mode
debug = true

# Leave host as 0.0.0.0, don't change it.
host = '0.0.0.0'

[js-module]
global-webcrypto = true
global-fetch = true

[voice]
bitrate = 64000
